[tool.poetry]
name = "ss"
version = "0.1.0"
description = "super start"
authors = ["ian luo <ianluo63@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
ss = "ss.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
