sdk:
  languase: python 
  version: 3.8
  packages:
    default:
      - typer
    development:
      - pynvim

dependencies:
  default:
    - django
  development:
    - pytest

units:
  - postgres

# this is the official nixpkgs ref
ref: xxxxx
