sdk:
  language: python 
  version: "3.8"
  packages:
    default:
      - typer
    development:
      - pynvim

dependencies:
  default:
    - django
  development:
    - black

units:
  - postgres:
      username: "test_user"
      password: "test_password"
      database: "test_database"
      host: ""
      folder: ""

# this is the official nixpkgs ref
rev: xxxxx
